name: Matrix Testing
on: workflow_dispatch
jobs:
  Matrix-Job:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [12,14,16]
        operating_system: [ubuntu-latest,windows-latest]
        exclude:
          - node-version: 12
            operating_system: windows-latest
          - node-version: 12
            operating_system: ubuntu-latest
        include:
          - node-version: 18
            operating_system: ubuntu-latest        
    runs-on: ${{matrix.operating_system}}
    steps:
      - name: clone the current repo
        uses: actions/checkout@v4
      - name: install nodeJS
        uses: actions/setup-node@v3
        with: 
          node-version: ${{matrix.node-version}}
      - name: install the npm depemdemcy
        run: npm ci
      - name: npm Test Code
        run: npm run test
      - name: upload the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: npm-test-reports
          path: test.json
