name: Node Js compile
on: workflow_dispatch
jobs:
  nodejob:
    runs-on: ubuntu-latest
    steps:
       - name: clone the repo
         uses: actions/checkout@v4
       - name: install dependencies
         run: npm ci
       - name: Make the report
         run: npm lint
       - name: Test the code
         run: npm run test 
    
  
